version: "3.6"

services:
  mongo:
    image: mongo
    command: mongod --port 27017
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ../mongodb/db:/data/db

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: server
    depends_on:
      - mongo
    restart: always
    ports:
      - "8000:8000"
    links:
      - mongo
    logging:
      driver: json-file
      options:
        max-size: "20m" # 单个文件大小为20m
        max-file: "10" # 最多10个文件
  
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: web
    depends_on:
      - server
    restart: always
    ports:
      - "7777:80"
    links:
      - server
    command: [ 'nginx', '-g', 'daemon off;' ]
